version: '3.7'

services:
    web:
        image: lorisleiva/laravel-docker
        command: php artisan serve --host=0.0.0.0
        ports:
            - 8000:8000
        volumes:
            - ./:/var/www

    database:
        image: mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=three_price_check
            - MYSQL_ROOT_PASSWORD=three
